#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

RED='\035[1;35m'
NC='\033[0m' # No Color
printf "${RED}1. Build documentation${NC}"
npm run build-docs

printf "${RED}2. Check format of staged documents${NC}"
npx lint-staged

printf "${RED}3. Run eslint${NC}"
npm run eslint

printf "${RED}4. Run unit tests${NC}"
npm test
