#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

purple=`tput setaf 5`
white=`tput setab 7`
bold=`tput bold`
reset=`tput sgr0`

echo "${white}${purple}${bold}--- Husky pre-commit checks ---${reset}\n"

echo "${purple}${bold}1. Build documentation${reset}"
npm run build-docs

echo  "${purple}${bold}2. Check format of staged documents${reset}"
npx lint-staged

echo  "${purple}${bold}3. Run eslint${reset}"
npm run eslint

echo  "${purple}${bold}4. Run unit tests${reset}"
npm test
